### ISSUE TITLE
`npm run dist` fails (no dist task in gulpfile)

### ISSUE THREAD

**Issue by jasonkarns** [socialally/browser-cookie#3]
I'm not entirely sure how this gulp setup is supposed to be structured. There doesn't appear to be a `dist` gulp task (which the `dist` npm script is attempting to run).  There's a `dist` key in gulp/config.js but I'm not certain how this is supposed to be used; especially since it references gulp/build/global.js which doesn't exist, either.

**Comment by tmpfs** [comment]
Sorry about that, it was legacy obsolete code that has been removed in 772af5cfb5b284a3d7563a2de5427a7c4bfa4e9b.
